### Get zaken and set a zaak url
< {%
    import {setOpenZaakHeaders} from "../openzaak-jwt.js"

    setOpenZaakHeaders(request, client);
%}

GET {{openzaak_host}}/zaken/api/v1/zaken

> {%
    const json = response.body;
    const zaak_url = json.results[0].url.replace('host.docker.internal', 'localhost');
    client.global.set("zaak_url", zaak_url);
%}

### Create Enkelvoudiginformatieobjecten
< {%
    import {setOpenZaakHeaders} from "../openzaak-jwt.js"

    setOpenZaakHeaders(request, client);
    client.global.set("creatiedatum", new Date().toISOString().split("T")[0]);
%}
POST {{openzaak_host}}documenten/api/v1/enkelvoudiginformatieobjecten
Content-Type: application/json

< ./bodies/enkelvoudiginformatieobject.json

> {%
    const json = response.body;
    client.global.set("informatieobject_url", json.url);
%}

### Maak zaakinformatie object aan en koppel enkelvoudiginformatieobject aan Zaak
< {%
    const vernietigingsdatum = new Date();
    vernietigingsdatum.setFullYear(vernietigingsdatum.getFullYear() + 1);
    client.global.set("vernietigingsdatum", vernietigingsdatum.toISOString());
    client.log("informatieobject_url: " + client.global.get("informatieobject_url"));
    import {setOpenZaakHeaders} from "../openzaak-jwt.js"
    setOpenZaakHeaders(request, client);
%}

POST {{openzaak_host}}zaken/api/v1/zaakinformatieobjecten
Content-Type: application/json

< ./bodies/zaakinformatieobject.json
